# Generated by Django 4.1.5 on 2023-04-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('mail_address', models.EmailField(max_length=254)),
                ('login_type', models.CharField(max_length=20)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
